Fix null.kill()
TypeError: Cannot call method 'kill' of null
    at Parent.disconnect (/home/ubuntu/workspace/node_modules/vfs-child/parent.js:65:15)
    at Parent.master.destroy (/home/ubuntu/workspace/plugins/c9.vfs.server/vfs.js:142:16) # Please
enter the commit message for your changes. Lines starting
    at Vfs.destroy (/home/ubuntu/workspace/plugins/c9.vfs.server/vfs.js:109:21) # with '#' will be
ignored, and an empty message aborts the commit.
    at EventEmitter.entry.destroy (/home/ubuntu/workspace/plugins/c9.vfs.server/cache.js:131:40) # On
branch fix-vfs
    at remove (/home/ubuntu/workspace/plugins/c9.vfs.server/cache.js:110:23) # Changes to be
committed:
    at null._onTimeout (/home/ubuntu/workspace/plugins/c9.vfs.server/cache.js:143:21) # modified:
node_modules/vfs-child/parent.js
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

                                                                   # Changes not staged for commit: